# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2022.

[package]
name = "earlgrey-cw310"
version.workspace = true
authors.workspace = true
build = "../../build.rs"
edition.workspace = true

[dependencies]
components = { path = "../../components" }
rv32i = { path = "../../../arch/rv32i" }
kernel = { path = "../../../kernel" }
earlgrey = { path = "../../../chips/earlgrey" }
lowrisc = { path = "../../../chips/lowrisc" }
tock-tbf = { path = "../../../libraries/tock-tbf" }

capsules-core = { path = "../../../capsules/core" }
capsules-extra = { path = "../../../capsules/extra" }
capsules-aes-gcm = { path = "../../../capsules/aes_gcm" }
capsules-system = { path = "../../../capsules/system" }


[features]
default = ["fpga_cw310"]

# OpenTitan SoC design can be synthesized or compiled for different targets. A
# target can be a specific FPGA board, an ASIC technology, or a simulation tool.
# Please see: https://docs.opentitan.org/doc/ug/getting_started/ for further
# information.
#
# OpenTitan CPU and possibly other components must be configured appropriately
# for a specific target:
#    - fpga_cw310:
#      OpenTitan SoC design running on CW310 FPGA.
#
#    - sim_verilator:
#      OpenTitan SoC design simulated in Verilator.
fpga_cw310 = []
sim_verilator = []
# This is used to indicate that we should include tests that only pass on
# hardware.
hardware_tests = []
